const projects = [
  {
    name: "Toolbox",
    description: "A collection of small, useful web-based utilities and tools.",
    href: "./projects/toolbox/",
    image: "./images/toolbox_thumbnail.webp",
    image1x: "./images/toolbox_thumbnail_1x.webp",
    status: "In Development",
    docHref: "./case-studies/toolbox.html",
    featured: true,
    date: "2025-10",
    deviceSupport: ["desktop", "mobile"],
    tags: ["Web"],
  },
  {
    name: "Island",
    description:
      "A Three.js scene where you drive a ship between islands, each representing a project.",
    href: "./projects/island/",
    image: "./images/island_thumbnail.webp",
    image1x: "./images/island_thumbnail_1x.webp",
    status: "On Hold",
    docHref: "./case-studies/island.html",
    featured: false,
    date: "2025-09",
    deviceSupport: ["desktop", "mobile"],
    tags: ["Web", "Three.js"],
  },
  {
    name: "Eneida",
    description:
      "An interactive portfolio terminal with commands, mini-games, and a windowing system.",
    href: "./projects/eneida/",
    image: "./images/eneida_thumbnail.webp",
    image1x: "./images/eneida_thumbnail_1x.webp",
    status: "Completed",
    docHref: "./case-studies/eneida.html",
    featured: true,
    date: "2025-07",
    deviceSupport: ["desktop"],
    tags: ["Web"],
  },
  {
    name: "Portal",
    description:
      "A visualization test featuring a video of a portal scanning animation.",
    href: "./projects/portal/",
    image: "./images/portal_thumbnail.webp",
    image1x: "./images/portal_thumbnail_1x.webp",
    status: "Completed",
    docHref: "./case-studies/portal.html",
    featured: false,
    date: "2025-07",
    deviceSupport: ["desktop", "mobile"],
    tags: ["Web"],
  },
  {
    name: "ASCII",
    description: "A simple video-to-ASCII art player.",
    href: "./projects/ASCII/",
    image: "./images/ASCII_thumbnail.webp",
    image1x: "./images/ASCII_thumbnail_1x.webp",
    status: "Completed",
    docHref: "./case-studies/ascii.html",
    featured: false,
    date: "2025-07",
    deviceSupport: ["desktop", "mobile"],
    tags: ["Web"],
  },
  {
    name: "Combat",
    description:
      "A tech demo for a turn-based combat system intended for a larger project.",
    href: "./projects/combat/",
    image: "./images/combat_thumbnail.webp",
    image1x: "./images/combat_thumbnail_1x.webp",
    status: "Completed",
    docHref: "./case-studies/combat.html",
    featured: false,
    date: "2025-06",
    deviceSupport: ["mobile"],
    tags: ["Web"],
  },
  {
    name: "Lockpick",
    description:
      "A tech demo for a lockpicking mini-game intended for a larger project.",
    href: "./projects/lockpick/",
    image: "./images/lockpick_thumbnail.webp",
    image1x: "./images/lockpick_thumbnail_1x.webp",
    status: "Completed",
    docHref: "./case-studies/lockpick.html",
    featured: false,
    date: "2025-06",
    deviceSupport: ["desktop", "mobile"],
    tags: ["Web"],
  },
  {
    name: "Textfall",
    description:
      "A small project featuring falling text that aligns into sentences.",
    href: "./projects/textfall/",
    image: "./images/textfall_thumbnail.webp",
    image1x: "./images/textfall_thumbnail_1x.webp",
    status: "Completed",
    docHref: "./case-studies/textfall.html",
    featured: false,
    date: "2025-03",
    deviceSupport: ["desktop"],
    tags: ["Web"],
  },
  {
    name: "Scrub GSAP",
    description:
      "A portfolio concept using GSAP for scroll-based animations and effects.",
    href: "./projects/scrub/",
    image: "./images/scrub_thumbnail.webp",
    image1x: "./images/scrub_thumbnail_1x.webp",
    status: "Archived",
    docHref: "./case-studies/scrub-gsap.html",
    featured: false,
    date: "2024-09",
    deviceSupport: ["desktop"],
    tags: ["Web", "GSAP"],
  },
  {
    name: "Particles",
    description:
      "A Three.js experiment displaying 3D objects as point clouds that react to mouse and scroll.",
    href: "./projects/particles/",
    image: "./images/particles_thumbnail.webp",
    image1x: "./images/particles_thumbnail_1x.webp",
    status: "Archived",
    docHref: "./case-studies/particles.html",
    featured: false,
    date: "2024-08",
    deviceSupport: ["desktop"],
    tags: ["Web", "Three.js"],
  },
  {
    name: "Platform Kinematics",
    description:
      "A real-time 3D simulator for a 3-axis Stewart platform, demonstrating inverse kinematics with React and Three.js.",
    href: "./projects/platform/",
    image: "./images/platform_thumbnail.webp",
    image1x: "./images/platform_thumbnail_1x.webp",
    status: "In Development",
    docHref: "./case-studies/platform.html",
    featured: true,
    date: "2025-10",
    deviceSupport: ["desktop", "mobile"],
    tags: ["React", "Three.js", "3D"],
  },
  {
    name: "uSeek",
    description:
      "A pirate-styled adventure puzzle game where you solve challenges to find a final code.",
    href: "./projects/uSeek/",
    image: "./images/useek_thumbnail.webp",
    image1x: "./images/useek_thumbnail_1x.webp",
    status: "Completed",
    docHref: "./case-studies/useek.html",
    featured: false,
    date: "2024-01",
    deviceSupport: ["desktop"],
    tags: ["Web"],
  },
];

export default projects;
